### PR TITLE
Support custom attributes for CSS and JS includes

### LINKED ISSUE #1: Setting additional (data-)attributes on the rendered script/link tag
It would be nice to be able to set additional attributes on the rendered script/link tags.

In our case, we want to specify "rel" and "title", and also "data-contrast" to indicate that our stylesheet is for the contrast option.

It would be good to change the HTL helper, for example by allowing the specification of a map (or similar), so that any attributes can be specified and we don't have to deal with a hardcoded list of supported attributes. This way, we don't have to do code changes when something new needs to be supported.

### PR DESCRIPTION
**Pull request by stefanseifert**
Fixes #1

Examples:
```html
<sly data-sly-use.clientlib="/apps/wcm-io/wcm/ui/clientlibs/sightly/templates/clientlib.html"
    data-sly-call="${clientlib.css @ categories=['my-clientlib-category'],
    customAttributes=['attr1=value 1','data-attr2=5','attr3']}"/>
```
```html
<sly data-sly-use.clientlib="/apps/wcm-io/wcm/ui/clientlibs/sightly/templates/clientlib.html"
    data-sly-call="${clientlib.js @ categories=['my-clientlib-category'],
    customAttributes=['attr1=value 1','data-attr2=5','attr3']}"/>
```

### CODE REVIEW

**Comment by gouravmakhija18** [comment]
@stefanseifert - I am curious to know only one question ?.

Why to use "customAttributes" instead to have "categories" same as JSInclude?.

**Note:** We have predefined attribute for link rel and giving flexibility to have any attribute can pollute clientlibs inclusion in code too ?

e.g.
We have only below combinations available.

**Case 1**: "rel" attribute can have only "prefetch | preload | preconnect | dns-prefetch | prerender | modulepreload"
**Case 2**: "as" attribute can have only "style | script | document | font | image | video | fetch"
**Case 3**: "crossorigin" attribute implementation is already there in [JSInclude.java](https://github.com/wcm-io/io.wcm.wcm.ui.clientlibs/blob/develop/src/main/java/io/wcm/wcm/ui/clientlibs/components/JSInclude.java) but same is not defined in [CSSInclude.java](https://github.com/wcm-io/io.wcm.wcm.ui.clientlibs/blob/develop/src/main/java/io/wcm/wcm/ui/clientlibs/components/CSSInclude.java) 
**Case 4**: Not sure in JSInclude.java & CSSInclude.java file have support for only .css or .js file or other below mention combinations can be possible.

### Different "rel" attribute variations
```
<link rel="prefetch" href="/style.css" />
<link rel="preload" href="/style.css" />
<link rel="preconnect" href="https://example.com" />
<link rel="dns-prefetch" href="https://example.com" />
<link rel="prerender" href="https://example.com/about.html" />
<link rel="modulepreload" href="/script.js" />
```
### Different "as" attribute variations

```
<link rel="prefetch" href="/articles/" as="document">
<link rel="prefetch" href="/public/app.js" as="script">
<link rel="prefetch" href="/style.css" as="style" />

<link rel="preload" href="/assets/Adobe-Clean.woff2" as="font" type="font/woff2" crossorigin />
<link rel="preload" href="dummy.png" as="image" />
<link rel="preload" href="https://cdn.com/small-file.mp4" as="video" />
<link rel="preload" href="https://cdn.com/file_1.webm" as="fetch" />
```

Reference link: https://www.debugbear.com/blog/resource-hints-rel-preload-prefetch-preconnect

**Comment by stefanseifert** [comment]
we currently have a set of HTML Standard attributes supported out of the box, with validation to ensure only valid property values are used, see https://wcm.io/wcm/ui/clientlibs/usage.html

for completely custom attributes like "data-contrast" as listed as example in #1 this PR can help.

maybe there as some HTML standard attributes we currently do not support out of the box we should add support for? the examples you are listing point in this direction - can you create a separate issues for this, that would be a separate PR.

**Comment by gouravmakhija18** [comment]
> we currently have a set of HTML Standard attributes supported out of the box, with validation to ensure only valid property values are used, see https://wcm.io/wcm/ui/clientlibs/usage.html
> 
> for completely custom attributes like "data-contrast" as listed as example in #1 this PR can help.
> 
> maybe there as some HTML standard attributes we currently do not support out of the box we should add support for? the examples you are listing point in this direction - can you create a separate issues for this, that would be a separate PR.

Thanks @stefanseifert for the quick response. I have created separate issue for above - https://github.com/wcm-io/io.wcm.wcm.ui.clientlibs/issues/3

**Comment by henrykuijpers** [comment]
Looks good to me, @stefanseifert !

**Pull request merged**
